services:


  web-app:
    image: "bblue/web-app:latest"
    container_name: web-app
    ports:
      - "9010:9010"

  configserver:
    image: "bblue/configserver:latest"
    container_name: configserver
    ports:
      - "8071:8071"

networks:
  healthcare:
    driver: "bridge"