spring:
  application:
    name: "web-app"
  config:
    import: "optional:configserver:http://localhost:8071/"

server:
  port: 9010
eureka:
  instance:
    preferIpAddress:true
  client:

    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: "web-app"
    description: "Healthcare web-app scoring Application"
    version: "1.0.0"






